import { sumOfAllGalacticPathLengths } from ".";

const sampleGalaxyMap = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`;

test("全ての銀河間の最短経路数の合計を算出する", () => {
  const actual = sumOfAllGalacticPathLengths(sampleGalaxyMap);
  expect(actual).toBe(8410);
});
